meique = Executable:new("meique")
meique:useTarget(lua)
meique:addLinkLibraries("pthread")
meique:addFiles([[
main.cpp
meique.cpp
logger.cpp
meiquescript.cpp
config.cpp
luastate.cpp
stdstringsux.cpp
compilerfactory.cpp
compiler.cpp
gcc.cpp
compileroptions.cpp
linkeroptions.cpp
target.cpp
luatarget.cpp
compilabletarget.cpp
executabletarget.cpp
librarytarget.cpp
customtarget.cpp
maintarget.cpp
os_unix.cpp
filehash.cpp
job.cpp
oscommandjob.cpp
luajob.cpp
jobqueue.cpp
jobmanager.cpp
graph.cpp
luacpputil.cpp
lualocker.cpp
]])
